create table "public"."employee" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null,
    "contract" smallint not null default '100'::smallint,
    "team_id" bigint not null
);


alter table "public"."employee" enable row level security;

create table "public"."employee_roles" (
    "employee_id" bigint not null,
    "role_id" bigint not null,
    "team_id" bigint not null
);


alter table "public"."employee_roles" enable row level security;

create table "public"."role" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null,
    "color" text,
    "shortname" text,
    "priority" boolean not null default false,
    "team_id" bigint not null
);


alter table "public"."role" enable row level security;

create table "public"."shift" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "date" date not null,
    "valid" boolean not null default false,
    "team_id" bigint not null
);


alter table "public"."shift" enable row level security;

create table "public"."team" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "owner_id" uuid not null default auth.uid()
);


alter table "public"."team" enable row level security;

create table "public"."team_users" (
    "team_id" bigint not null,
    "user_id" uuid not null
);


alter table "public"."team_users" enable row level security;

create table "public"."timeslot" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "shift_id" bigint not null,
    "role_id" bigint,
    "employee_id" bigint,
    "start_time" time without time zone not null,
    "end_time" time without time zone not null,
    "break" boolean not null default false,
    "team_id" bigint not null
);


alter table "public"."timeslot" enable row level security;

create table "public"."vacation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "employee_id" bigint not null,
    "date" date not null,
    "team_id" bigint not null
);


alter table "public"."vacation" enable row level security;

CREATE UNIQUE INDEX employee_pkey ON public.employee USING btree (id);

CREATE UNIQUE INDEX employee_roles_pkey ON public.employee_roles USING btree (employee_id, role_id);

CREATE UNIQUE INDEX role_pkey ON public.role USING btree (id);

CREATE UNIQUE INDEX shift_pkey ON public.shift USING btree (id);

CREATE UNIQUE INDEX team_pkey ON public.team USING btree (id);

CREATE UNIQUE INDEX team_users_pkey ON public.team_users USING btree (team_id, user_id);

CREATE UNIQUE INDEX timeslot_pkey ON public.timeslot USING btree (id);

CREATE UNIQUE INDEX vacation_pkey ON public.vacation USING btree (id);

alter table "public"."employee" add constraint "employee_pkey" PRIMARY KEY using index "employee_pkey";

alter table "public"."employee_roles" add constraint "employee_roles_pkey" PRIMARY KEY using index "employee_roles_pkey";

alter table "public"."role" add constraint "role_pkey" PRIMARY KEY using index "role_pkey";

alter table "public"."shift" add constraint "shift_pkey" PRIMARY KEY using index "shift_pkey";

alter table "public"."team" add constraint "team_pkey" PRIMARY KEY using index "team_pkey";

alter table "public"."team_users" add constraint "team_users_pkey" PRIMARY KEY using index "team_users_pkey";

alter table "public"."timeslot" add constraint "timeslot_pkey" PRIMARY KEY using index "timeslot_pkey";

alter table "public"."vacation" add constraint "vacation_pkey" PRIMARY KEY using index "vacation_pkey";

alter table "public"."employee" add constraint "employee_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."employee" validate constraint "employee_team_id_fkey";

alter table "public"."employee_roles" add constraint "employee_roles_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."employee_roles" validate constraint "employee_roles_employee_id_fkey";

alter table "public"."employee_roles" add constraint "employee_roles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES role(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."employee_roles" validate constraint "employee_roles_role_id_fkey";

alter table "public"."employee_roles" add constraint "employee_roles_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."employee_roles" validate constraint "employee_roles_team_id_fkey";

alter table "public"."role" add constraint "role_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."role" validate constraint "role_team_id_fkey";

alter table "public"."shift" add constraint "shift_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."shift" validate constraint "shift_team_id_fkey";

alter table "public"."team" add constraint "team_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team" validate constraint "team_owner_id_fkey";

alter table "public"."team_users" add constraint "team_users_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_users" validate constraint "team_users_team_id_fkey";

alter table "public"."team_users" add constraint "team_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_users" validate constraint "team_users_user_id_fkey";

alter table "public"."timeslot" add constraint "timeslot_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."timeslot" validate constraint "timeslot_employee_id_fkey";

alter table "public"."timeslot" add constraint "timeslot_role_id_fkey" FOREIGN KEY (role_id) REFERENCES role(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."timeslot" validate constraint "timeslot_role_id_fkey";

alter table "public"."timeslot" add constraint "timeslot_shift_id_fkey" FOREIGN KEY (shift_id) REFERENCES shift(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."timeslot" validate constraint "timeslot_shift_id_fkey";

alter table "public"."timeslot" add constraint "timeslot_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."timeslot" validate constraint "timeslot_team_id_fkey";

alter table "public"."vacation" add constraint "vacation_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vacation" validate constraint "vacation_employee_id_fkey";

alter table "public"."vacation" add constraint "vacation_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vacation" validate constraint "vacation_team_id_fkey";

grant delete on table "public"."employee" to "anon";

grant insert on table "public"."employee" to "anon";

grant references on table "public"."employee" to "anon";

grant select on table "public"."employee" to "anon";

grant trigger on table "public"."employee" to "anon";

grant truncate on table "public"."employee" to "anon";

grant update on table "public"."employee" to "anon";

grant delete on table "public"."employee" to "authenticated";

grant insert on table "public"."employee" to "authenticated";

grant references on table "public"."employee" to "authenticated";

grant select on table "public"."employee" to "authenticated";

grant trigger on table "public"."employee" to "authenticated";

grant truncate on table "public"."employee" to "authenticated";

grant update on table "public"."employee" to "authenticated";

grant delete on table "public"."employee" to "service_role";

grant insert on table "public"."employee" to "service_role";

grant references on table "public"."employee" to "service_role";

grant select on table "public"."employee" to "service_role";

grant trigger on table "public"."employee" to "service_role";

grant truncate on table "public"."employee" to "service_role";

grant update on table "public"."employee" to "service_role";

grant delete on table "public"."employee_roles" to "anon";

grant insert on table "public"."employee_roles" to "anon";

grant references on table "public"."employee_roles" to "anon";

grant select on table "public"."employee_roles" to "anon";

grant trigger on table "public"."employee_roles" to "anon";

grant truncate on table "public"."employee_roles" to "anon";

grant update on table "public"."employee_roles" to "anon";

grant delete on table "public"."employee_roles" to "authenticated";

grant insert on table "public"."employee_roles" to "authenticated";

grant references on table "public"."employee_roles" to "authenticated";

grant select on table "public"."employee_roles" to "authenticated";

grant trigger on table "public"."employee_roles" to "authenticated";

grant truncate on table "public"."employee_roles" to "authenticated";

grant update on table "public"."employee_roles" to "authenticated";

grant delete on table "public"."employee_roles" to "service_role";

grant insert on table "public"."employee_roles" to "service_role";

grant references on table "public"."employee_roles" to "service_role";

grant select on table "public"."employee_roles" to "service_role";

grant trigger on table "public"."employee_roles" to "service_role";

grant truncate on table "public"."employee_roles" to "service_role";

grant update on table "public"."employee_roles" to "service_role";

grant delete on table "public"."role" to "anon";

grant insert on table "public"."role" to "anon";

grant references on table "public"."role" to "anon";

grant select on table "public"."role" to "anon";

grant trigger on table "public"."role" to "anon";

grant truncate on table "public"."role" to "anon";

grant update on table "public"."role" to "anon";

grant delete on table "public"."role" to "authenticated";

grant insert on table "public"."role" to "authenticated";

grant references on table "public"."role" to "authenticated";

grant select on table "public"."role" to "authenticated";

grant trigger on table "public"."role" to "authenticated";

grant truncate on table "public"."role" to "authenticated";

grant update on table "public"."role" to "authenticated";

grant delete on table "public"."role" to "service_role";

grant insert on table "public"."role" to "service_role";

grant references on table "public"."role" to "service_role";

grant select on table "public"."role" to "service_role";

grant trigger on table "public"."role" to "service_role";

grant truncate on table "public"."role" to "service_role";

grant update on table "public"."role" to "service_role";

grant delete on table "public"."shift" to "anon";

grant insert on table "public"."shift" to "anon";

grant references on table "public"."shift" to "anon";

grant select on table "public"."shift" to "anon";

grant trigger on table "public"."shift" to "anon";

grant truncate on table "public"."shift" to "anon";

grant update on table "public"."shift" to "anon";

grant delete on table "public"."shift" to "authenticated";

grant insert on table "public"."shift" to "authenticated";

grant references on table "public"."shift" to "authenticated";

grant select on table "public"."shift" to "authenticated";

grant trigger on table "public"."shift" to "authenticated";

grant truncate on table "public"."shift" to "authenticated";

grant update on table "public"."shift" to "authenticated";

grant delete on table "public"."shift" to "service_role";

grant insert on table "public"."shift" to "service_role";

grant references on table "public"."shift" to "service_role";

grant select on table "public"."shift" to "service_role";

grant trigger on table "public"."shift" to "service_role";

grant truncate on table "public"."shift" to "service_role";

grant update on table "public"."shift" to "service_role";

grant delete on table "public"."team" to "anon";

grant insert on table "public"."team" to "anon";

grant references on table "public"."team" to "anon";

grant select on table "public"."team" to "anon";

grant trigger on table "public"."team" to "anon";

grant truncate on table "public"."team" to "anon";

grant update on table "public"."team" to "anon";

grant delete on table "public"."team" to "authenticated";

grant insert on table "public"."team" to "authenticated";

grant references on table "public"."team" to "authenticated";

grant select on table "public"."team" to "authenticated";

grant trigger on table "public"."team" to "authenticated";

grant truncate on table "public"."team" to "authenticated";

grant update on table "public"."team" to "authenticated";

grant delete on table "public"."team" to "service_role";

grant insert on table "public"."team" to "service_role";

grant references on table "public"."team" to "service_role";

grant select on table "public"."team" to "service_role";

grant trigger on table "public"."team" to "service_role";

grant truncate on table "public"."team" to "service_role";

grant update on table "public"."team" to "service_role";

grant delete on table "public"."team_users" to "anon";

grant insert on table "public"."team_users" to "anon";

grant references on table "public"."team_users" to "anon";

grant select on table "public"."team_users" to "anon";

grant trigger on table "public"."team_users" to "anon";

grant truncate on table "public"."team_users" to "anon";

grant update on table "public"."team_users" to "anon";

grant delete on table "public"."team_users" to "authenticated";

grant insert on table "public"."team_users" to "authenticated";

grant references on table "public"."team_users" to "authenticated";

grant select on table "public"."team_users" to "authenticated";

grant trigger on table "public"."team_users" to "authenticated";

grant truncate on table "public"."team_users" to "authenticated";

grant update on table "public"."team_users" to "authenticated";

grant delete on table "public"."team_users" to "service_role";

grant insert on table "public"."team_users" to "service_role";

grant references on table "public"."team_users" to "service_role";

grant select on table "public"."team_users" to "service_role";

grant trigger on table "public"."team_users" to "service_role";

grant truncate on table "public"."team_users" to "service_role";

grant update on table "public"."team_users" to "service_role";

grant delete on table "public"."timeslot" to "anon";

grant insert on table "public"."timeslot" to "anon";

grant references on table "public"."timeslot" to "anon";

grant select on table "public"."timeslot" to "anon";

grant trigger on table "public"."timeslot" to "anon";

grant truncate on table "public"."timeslot" to "anon";

grant update on table "public"."timeslot" to "anon";

grant delete on table "public"."timeslot" to "authenticated";

grant insert on table "public"."timeslot" to "authenticated";

grant references on table "public"."timeslot" to "authenticated";

grant select on table "public"."timeslot" to "authenticated";

grant trigger on table "public"."timeslot" to "authenticated";

grant truncate on table "public"."timeslot" to "authenticated";

grant update on table "public"."timeslot" to "authenticated";

grant delete on table "public"."timeslot" to "service_role";

grant insert on table "public"."timeslot" to "service_role";

grant references on table "public"."timeslot" to "service_role";

grant select on table "public"."timeslot" to "service_role";

grant trigger on table "public"."timeslot" to "service_role";

grant truncate on table "public"."timeslot" to "service_role";

grant update on table "public"."timeslot" to "service_role";

grant delete on table "public"."vacation" to "anon";

grant insert on table "public"."vacation" to "anon";

grant references on table "public"."vacation" to "anon";

grant select on table "public"."vacation" to "anon";

grant trigger on table "public"."vacation" to "anon";

grant truncate on table "public"."vacation" to "anon";

grant update on table "public"."vacation" to "anon";

grant delete on table "public"."vacation" to "authenticated";

grant insert on table "public"."vacation" to "authenticated";

grant references on table "public"."vacation" to "authenticated";

grant select on table "public"."vacation" to "authenticated";

grant trigger on table "public"."vacation" to "authenticated";

grant truncate on table "public"."vacation" to "authenticated";

grant update on table "public"."vacation" to "authenticated";

grant delete on table "public"."vacation" to "service_role";

grant insert on table "public"."vacation" to "service_role";

grant references on table "public"."vacation" to "service_role";

grant select on table "public"."vacation" to "service_role";

grant trigger on table "public"."vacation" to "service_role";

grant truncate on table "public"."vacation" to "service_role";

grant update on table "public"."vacation" to "service_role";


